name: generate status

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  generate-status:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Status
        run: |
          echo "🐦‍🔥 training"
